/**
 * Copyright (c) 2025 Beijing Volcano Engine Technology Co., Ltd. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.volcengine.veadk.example;

import static java.nio.charset.StandardCharsets.UTF_8;

import com.google.adk.agents.BaseAgent;
import com.google.adk.agents.LlmAgent;
import com.google.adk.agents.RunConfig;
import com.google.adk.events.Event;
import com.google.adk.sessions.Session;
import com.google.genai.types.Content;
import com.google.genai.types.Part;
import com.volcengine.veadk.knowledgebase.KnowledgeBase;
import com.volcengine.veadk.model.ArkLlm;
import com.volcengine.veadk.runner.Runner;
import com.volcengine.veadk.tools.knowledgebase.LoadKnowledgebaseTool;
import io.reactivex.rxjava3.core.Flowable;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import org.apache.commons.lang3.StringUtils;

public class OpensearchKnowledgebaseAgent {

    private static final String APP_NAME = "opensearch_knowledgebase_agent";
    private static final String MODEL_ID = "deepseek-v4-flash-260425";
    private static final String DEFAULT_INDEX = "opensearch_knowledgebase_agent";
    private static final List<String> DEFAULT_KNOWLEDGE =
            List.of(
                    """
                    VeADK OpenSearch knowledgebase example:
                    The OpenSearch knowledgebase stores local documents as vector chunks. Developers
                    configure OpenSearch with DATABASE_OPENSEARCH_HOST, DATABASE_OPENSEARCH_PORT,
                    DATABASE_OPENSEARCH_USERNAME, and DATABASE_OPENSEARCH_PASSWORD. Embeddings are
                    generated by Ark through MODEL_EMBEDDING_API_KEY.
                    """,
                    """
                    Demo support policy:
                    Internal support tickets tagged P0 should be acknowledged within 15 minutes.
                    P1 tickets should be acknowledged within 2 hours. Non-urgent requests should
                    include product name, region, account id, and a short reproduction description.
                    """,
                    """
                    Demo reimbursement policy:
                    Team members can submit meal reimbursements for business travel. Receipts must
                    include date, amount, merchant, and attendee names. Reimbursement requests should
                    be submitted within 30 days after the trip ends.
                    """);

    public static void main(String[] args) throws IOException {
        try (KnowledgeBase opensearchKnowledge =
                KnowledgeBase.builder().index(resolveIndex()).topK(5).build()) {
            loadKnowledgebaseDocuments(opensearchKnowledge, args);

            BaseAgent agent =
                    LlmAgent.builder()
                            .name(APP_NAME)
                            .description("A helpful assistant with an OpenSearch knowledgebase.")
                            .instruction(
                                    """
                                    Answer user questions to the best of your knowledge.
                                    Use loadKnowledgebase first when the user asks about VeADK
                                    OpenSearch setup, support policy, reimbursement policy, or any
                                    documents loaded into the OpenSearch knowledgebase.
                                    """)
                            .model(new ArkLlm(MODEL_ID))
                            .tools(new LoadKnowledgebaseTool(opensearchKnowledge))
                            .build();

            Runner runner = new Runner(agent);
            RunConfig runConfig =
                    RunConfig.builder().setStreamingMode(RunConfig.StreamingMode.NONE).build();

            String userId = "user";
            String sessionId = "opensearch-knowledgebase-session";
            Session session =
                    runner.sessionService()
                            .createSession(runner.appName(), userId, null, sessionId)
                            .blockingGet();

            try (Scanner scanner = new Scanner(System.in, UTF_8)) {
                while (true) {
                    System.out.print("\nYou > ");
                    String userInput = scanner.nextLine();
                    if ("quit".equalsIgnoreCase(userInput)) {
                        break;
                    }

                    Content userMsg = Content.fromParts(Part.fromText(userInput));
                    Flowable<Event> events =
                            runner.runAsync(session.userId(), session.id(), userMsg, runConfig);

                    events.blockingForEach(
                            event -> {
                                if (event.finalResponse()) {
                                    System.out.println("\nAgent > " + event.stringifyContent());
                                }
                            });
                }
            }
        }
    }

    private static String resolveIndex() {
        String index = System.getenv("DATABASE_OPENSEARCH_INDEX");
        return StringUtils.isBlank(index) ? DEFAULT_INDEX : index;
    }

    private static void loadKnowledgebaseDocuments(KnowledgeBase knowledgeBase, String[] args)
            throws IOException {
        if (args == null || args.length == 0) {
            System.out.println(
                    "No documents provided. Loading built-in demo knowledge into OpenSearch.");
            knowledgeBase.addFromText(DEFAULT_KNOWLEDGE);
            System.out.println(
                    "You can also pass docs/opensearch-knowledgebase-test-qa.md as an argument.");
            System.out.println(
                    "Try asking: \"How quickly should a P0 support ticket be acknowledged?\"");
            return;
        }

        List<String> files = new ArrayList<>();
        for (String arg : args) {
            Path path = Path.of(arg);
            if (Files.isDirectory(path)) {
                knowledgeBase.addFromDirectory(path.toString());
            } else if (Files.isRegularFile(path)) {
                files.add(path.toString());
            } else {
                System.out.println("Skip missing path: " + path);
            }
        }
        if (!files.isEmpty()) {
            knowledgeBase.addFromFiles(files);
        }
    }
}
